http_server:
  port: 15340

repository:
  postgres:
    username:
    password:
    host:
    port:
    dbname:

language:
  default: en
  core: en

logger:
  level: debug
  encoding: json
  output_path: logs/app.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
