version: "3"

includes:
  docs: ./docs
  git-hooks: ./cmd/hooks

tasks:
  dev:
    - task: docs:generate
    - air

  test:
    cmd: go test -v {{.CLI_ARGS}}

  test:cover:
    cmds:
      - go test -v -coverprofile=prof.out {{.CLI_ARGS}}
      - go tool cover -html=prof.out

  setup:
    cmds:
      - task: setup-air
      - task: git-hooks:setup-git-hooks
      - task: docs:setup-swag

  setup-air:
    internal: true
    cmd: go install github.com/air-verse/air@v1.61.5
